// Copyright (c) 2021 IBM Corporation and others.
// Licensed under Creative Commons Attribution-NoDerivatives
// 4.0 International (CC BY-ND 4.0)
//   https://creativecommons.org/licenses/by-nd/4.0/
//
// Contributors:
//     IBM Corporation
//
:projectid: graphql-client
:page-layout: guide-multipane
:page-duration: 20 minutes
:page-releasedate: 2021-11-11
:page-essential: false
:page-description: Learn how to use a GraphQL client to run GraphQL queries and mutations.
:page-tags: ['MicroProfile', 'Jakarta EE']
:page-related-guides: ['graphql-intro']
:page-permalink: /guides/{projectid}
:common-includes: https://raw.githubusercontent.com/OpenLiberty/guides-common/prod
:imagesdir: /img/guide/{projectid}
:source-highlighter: prettify
:page-seo-title: Implementing a GraphQL client microservice to run GraphQL queries and mutations
:page-seo-description: A tutorial with examples on how to use the third-party Smallrye GraphQL client API to run GraphQL queries and mutations
:guide-author: Open Liberty
= Running GraphQL queries and mutations using a GraphQL client

[.hidden]
NOTE: This repository contains the guide documentation source. To view the guide in published form,
view it on the https://openliberty.io/guides/{projectid}.html[Open Liberty website].

Learn how to use a GraphQL client to run GraphQL queries and mutations.

== What you'll learn

You will learn how to create a GraphQL client microservice.

GraphQL is an open source data query language.
Unlike REST APIs, each `POST` request sent to a GraphQL service goes to a single HTTP endpoint.
To learn more about GraphQL, see our https://openliberty.io/guides/graphql-intro.html[GraphQL intro guide^].

You'll start with the GraphQL service created as part of our GraphQL intro guide.
You'll then use the https://github.com/smallrye/smallrye-graphql/tree/main/client/api[SmallRye GraphQL client^]
to create a `client` microservice that will make requests to the GraphQL service.
OpenAPI will be used to help make the requests and display the data.
To learn more about OpenAPI, check out the 
https://openliberty.io/guides/microprofile-openapi.html[Documenting RESTful APIs] guide.

== Additional prerequisites

Before you begin, Docker needs to be installed.
For installation instructions, refer to the https://docs.docker.com/get-docker/[official Docker documentation^].
You will build and run the application in Docker containers.

Make sure to start your Docker daemon before you proceed.

///////////////////////////
// Getting started
///////////////////////////

== Implementing system service

Navigate to the `start/system` directory 

[role='command']
include::{common-includes}/gitclone.adoc[]

// No "Try what you'll build" because of multiple services, will take too long



== Great work! You're done!

You just created a GraphQL client microservce!

include::{common-includes}/attribution.adoc[]

// ------------ END ------------
