// Copyright (c) 2022 IBM Corporation and others.
// Licensed under Creative Commons Attribution-NoDerivatives
// 4.0 International (CC BY-ND 4.0)
//   https://creativecommons.org/licenses/by-nd/4.0/
//
// Contributors:
//     IBM Corporation
//
:projectid: graphql-client
:page-layout: guide-multipane
:page-duration: 20 minutes
:page-releasedate: 2021-11-11
:page-essential: false
:page-description: Learn how to use a GraphQL client to run GraphQL queries and mutations.
:page-tags: ['MicroProfile', 'Jakarta EE']
:page-related-guides: ['graphql-intro']
:page-permalink: /guides/{projectid}
:common-includes: https://raw.githubusercontent.com/OpenLiberty/guides-common/prod
:imagesdir: /img/guide/{projectid}
:source-highlighter: prettify
:page-seo-title: Implementing a GraphQL client microservice to run GraphQL queries and mutations
:page-seo-description: A tutorial with examples on how to use the third-party Smallrye GraphQL client API to run GraphQL queries and mutations
:guide-author: Open Liberty
= Running GraphQL queries and mutations using a GraphQL client

[.hidden]
NOTE: This repository contains the guide documentation source. To view the guide in published form,
view it on the https://openliberty.io/guides/{projectid}.html[Open Liberty website].

Learn how to use a GraphQL client to run GraphQL queries and mutations.

== What you'll learn

GraphQL is an open source data query language.
Unlike REST APIs, each request sent to a GraphQL service goes to a single HTTP endpoint.
To learn more about GraphQL, see the https://openliberty.io/guides/microprofile-graphql.html[Optimizing REST queries for microservices with GraphQL^] guide.

You will start with the `graphql` microservice created as part of the https://openliberty.io/guides/microprofile-graphql.html[Optimizing REST queries for microservices with GraphQL^] guide.
Then, you'll use the https://github.com/smallrye/smallrye-graphql#client[SmallRye GraphQL client^]
to create a `query` microservice that will make requests to the GraphQL microservice.
The GraphQL microservice retrieves data from multiple `system` microservices. 
The `query` microservice makes requests to the GraphQL microservice, which then makes requests to the `system` microservice.

The results of the requests will be displayed at REST endpoints.
OpenAPI will be used to help make the requests and display the data.
To learn more about OpenAPI, check out the 
https://openliberty.io/guides/microprofile-openapi.html[Documenting RESTful APIs] guide.

== Additional prerequisites

Before you begin, Docker needs to be installed.
For installation instructions, refer to the https://docs.docker.com/get-docker/[official Docker documentation^].
You will build and run the application in Docker containers.

Make sure to start your Docker daemon before you proceed.

///////////////////////////
// Getting started
///////////////////////////

[role='command']
include::{common-includes}/gitclone.adoc[]

// No "Try what you'll build" because of multiple services, will take too long

== Implementing a GraphQL client

Navigate to the `start` directory to begin.

The https://github.com/smallrye/smallrye-graphql#client[SmallRye GraphQL client^]
will be used to implement the GraphQL client service.
SmallRye GraphQL client supports two types of clients: typesafe and dynamic clients. 
A typesafe client provides ease of use and a high-level approach, while a dynamic client provides a more customizable and low-level approach to handle operations and responses. You will implement a typesafe client microservice. 

The typesafe client interface contains a function for each resolver available in the `graphql` microservice.
The JSON objects returned by the `graphql` microservice are converted to Java objects.

[role="code_command hotspot file=0" ,subs="quotes"]
----
#Create the `GraphQlClient` interface.#
`query/src/main/java/io/openliberty/guides/client/GraphQlClient.java`
----

The [hotspot file=0]`GraphQlClient` interface is annotated with the
[hotspot=clientApi file=0]`@GraphQlClientApi` annotation.
This annotation denotes that this interface is used to create a typesafe GraphQL client.

Inside the interface, a function header is written for each resolver available in the `graphql` microservice.
The names of the functions match the names of the resolvers in the GraphQL schema.
Resolvers that require input variables have the input variables passed in using the
[hotspot=systemInfo hotspot=systemLoad hotspot=editNote file=0]`@Name` annotation on the function inputs.
The return types of the functions should match those of the GraphQL resolvers.

For example, the [hotspot=systemInfo file=0]`system()` function maps to the `system` resolver.
The resolver returns a `SystemInfo` object, which is described by the `SystemInfo` class.
Thus, the [hotspot=systemInfo file=0]`system()` function returns the type `SystemInfo`.

Because the [hotspot=editNote file=0]`editNote` resolver is for a `mutation` operation,
it has the [hotspot=mutationTag file=0]`@Mutation` annotation on it.
A `mutation` operation allows you to modify data, in this case, it allows you to add and edit a note to the system service. 
If the hotspot=mutationTag file=0]`@Mutation` annotation was not placed on the function, it would be treated as if it mapped to a `query` operation.

[role="code_command hotspot file=1" ,subs="quotes"]
----
#Create the `QueryResource` class.#
`query/src/main/java/io/openliberty/guides/client/QueryResource.java`
----

The [hotspot file=1]`QueryResource` class uses the `GraphQlClient` interface
to make requests to the `graphql` microservice and display the results.
In a real application, you would be making requests to an external GraphQL API,
or you would be doing further manipulation of the data after retrieval.

Use the [hotspot=clientBuilder file=1]`GraphQLClientBuilder`] class to create a client object that implements the `GraphQlClient` interface and can interact with the `graphql` microservice.
The `GraphQlClient` client can make requests to the URL specified by the [hotspot=url file=3]`graphql.server` variable
in the `server.xml`.
The client is used in the [hotspot=clientUsed1 file=1]`querySystem()`,
[hotspot=clientUsed2 file=1]`querySystemLoad()`, and [hotspot=clientUsed3 file=1]`editNote()` functions.

Add the SmallRye GraphQL client dependency to the project configuration file.

[role="code_command hotspot file=2" ,subs="quotes"]
----
#Replace the Maven project file.#
`query/pom.xml`
----

The [hotspot=graphQLClientDependency file=2]`smallrye-graphql-client` dependency provides the classes that use to interact with a `graphql` microservice.

To get the service running, the Liberty server needs to be correctly configured.

[role="code_command hotspot file=3" ,subs="quotes"]
----
#Replace the server configuration file.#
`query/src/main/liberty/config/server.xml`
----

The [hotspot=url file=3]`graphql.server` variable is defined in the [hotspot file=3]`server.xml` file.
This variable defines where the GraphQL client makes requests to.

// file 0
GraphQlClient.java
[source, java, linenums, role='code_column hide_tags=copyright']
----
include::finish/query/src/main/java/io/openliberty/guides/client/GraphQlClient.java[]
----

// file 1
QueryResource.java
[source, java, linenums, role='code_column hide_tags=copyright']
----
include::finish/query/src/main/java/io/openliberty/guides/client/QueryResource.java[]
----

// file 2
pom.xml
[source, xml, linenums, role='code_column hide_tags=copyright']
----
include::finish/query/pom.xml[]
----

// file 3
server.xml
[source, xml, linenums, role='code_column hide_tags=copyright']
----
include::finish/query/src/main/liberty/config/server.xml[]
----

== Building and running the application

From the `start` directory, run the following commands:

[role='command']
----
mvn -pl models install
mvn package
----

The `mvn install` command compiles and packages the object types you created to a `.jar` file.
This allows them to be used by the `system` and `graphql` services.
The `mvn package` command packages the `system`, `graphql`, and `query` services to `.war` files. 

include::{common-includes}/ol-icr-full-docker-pull.adoc[]

Dockerfiles have already been set up for you.
Build your Docker images with the following commands:

[role='command']
----
docker build -t system:1.0-java8-SNAPSHOT --build-arg JAVA_VERSION=java8 system/.
docker build -t system:1.0-java11-SNAPSHOT --build-arg JAVA_VERSION=java11 system/.
docker build -t graphql:1.0-SNAPSHOT graphql/.
docker build -t query:1.0-SNAPSHOT query/.
----

Run these Docker images using the provided `startContainers` script.
The script will create a network for the services to communicate through.
It will create the two `system` microservices, a `graphql` microservice, and a `query` microservice that will interact with eachother.

include::{common-includes}/os-tabs.adoc[]

[.tab_content.windows_section]
--
[role='command']
```
.\scripts\startContainers.bat
```
--

[.tab_content.mac_section.linux_section]
--
[role='command']
```
./scripts/startContainers.sh
```
--

The containers may take some time to become available. 
Once your application is up and running, open your browser and check out your service by going to http://localhost:9084[^].

== Accessing the application

To access the client service, visit the http://localhost:9084/openapi/ui/[^] URL. 
This URL displays the available REST endpoints that test the API endpoints that you created.

**Try the query operations**

From the OpenAPI UI, test the read operation at the `GET /query/system/{hostname}` endpoint. 
This request retrieves the system properties for the `hostname` specified.

When the `hostname` is specified to `system-java8`. The response is similar to the following example:

[role='no_copy']
----
{
  "hostname": "system-java8",
  "java": {
    "vendor": "International Business Machines Corporation",
    "version": "1.8.0_312"
  },
  "osArch": "amd64",
  "osName": "Linux",
  "osVersion": "5.10.25-linuxkit",
  "systemMetrics": {
    "heapSize": 2086993920,
    "nonHeapSize": -1,
    "processors": 8
  },
  "username": "default"
}
----

You can try out the operations using the hostname `system-java11` as well. 

You can retrieve the information about the resource usage of any number of system services at the `GET /query/systemLoad/{hostnames}` endpoint. 
When the `hostnames` are specified to `system-java8,system-java11`. The response is similar to the following example:

[role='no_copy']
----
[
  {
    "hostname": "system-java8",
    "loadData": {
      "heapUsed": 34251904,
      "loadAverage": 0.11,
      "nonHeapUsed": 84034688
    }
  },
  {
    "hostname": "system-java11",
    "loadData": {
      "heapUsed": 41953280,
      "loadAverage": 0.11,
      "nonHeapUsed": 112506520
    }
  }
]
----

**Try the mutation operation**

You can also make requests to add a note to a system service at the `POST /query/mutation/system/note` endpoint.
To add a note to the system service running on Java 8, specify the following in the request body:

[role='command']
----
{
  "hostname": "system-java8",
  "text": "I'm trying out GraphQL on Open Liberty!"
}
----

You will recieve a `200` response code if the request is processed succesfully. 

== Tearing down the environment

When you're done checking out the application, run the following script to stop the application:

include::{common-includes}/os-tabs.adoc[]

[.tab_content.windows_section]
--
[role='command']
```
.\scripts\stopContainers.bat
```
--

[.tab_content.mac_section.linux_section]
--
[role='command']
```
./scripts/stopContainers.sh
```
--

== Great work! You're done!

You just created a GraphQL client microservce!

include::{common-includes}/attribution.adoc[]

// ------------ END ------------
