// Copyright (c) 2021 IBM Corporation and others.
// Licensed under Creative Commons Attribution-NoDerivatives
// 4.0 International (CC BY-ND 4.0)
//   https://creativecommons.org/licenses/by-nd/4.0/
//
// Contributors:
//     IBM Corporation
//
:projectid: graphql-client
:page-layout: guide-multipane
:page-duration: 20 minutes
:page-releasedate: 2021-11-11
:page-essential: false
:page-description: Learn how to use a GraphQL client to run GraphQL queries and mutations.
:page-tags: ['MicroProfile', 'Jakarta EE']
:page-related-guides: ['graphql-intro']
:page-permalink: /guides/{projectid}
:common-includes: https://raw.githubusercontent.com/OpenLiberty/guides-common/prod
:imagesdir: /img/guide/{projectid}
:source-highlighter: prettify
:page-seo-title: Implementing a GraphQL client microservice to run GraphQL queries and mutations
:page-seo-description: A tutorial with examples on how to use the third-party Smallrye GraphQL client API to run GraphQL queries and mutations
:guide-author: Open Liberty
= Running GraphQL queries and mutations using a GraphQL client

[.hidden]
NOTE: This repository contains the guide documentation source. To view the guide in published form,
view it on the https://openliberty.io/guides/{projectid}.html[Open Liberty website].

Learn how to use a GraphQL client to run GraphQL queries and mutations.

== What you'll learn

You will learn how to create a GraphQL client microservice.

GraphQL is an open source data query language.
Unlike REST APIs, each `POST` request sent to a GraphQL service goes to a single HTTP endpoint.
To learn more about GraphQL, see our https://openliberty.io/guides/graphql-intro.html[GraphQL intro guide^].

You'll start with the GraphQL service created as part of our GraphQL intro guide.
You'll then use the https://github.com/smallrye/smallrye-graphql/tree/main/client/api[SmallRye GraphQL client^]
to create a `client` microservice that will make requests to the GraphQL service.
OpenAPI will be used to help make the requests and display the data.
To learn more about OpenAPI, check out the 
https://openliberty.io/guides/microprofile-openapi.html[Documenting RESTful APIs] guide.

== Additional prerequisites

Before you begin, Docker needs to be installed.
For installation instructions, refer to the https://docs.docker.com/get-docker/[official Docker documentation^].
You will build and run the application in Docker containers.

Make sure to start your Docker daemon before you proceed.

///////////////////////////
// Getting started
///////////////////////////

[role='command']
include::{common-includes}/gitclone.adoc[]

// No "Try what you'll build" because of multiple services, will take too long

== Implementing a GraphQL client

Navigate to the `start` directory to begin.

The https://github.com/smallrye/smallrye-graphql/tree/main/client/api[SmallRye GraphQL client^]
will be used to implement the GraphQL client service.
A client interface will be created.
The interface will contain a function for each resolver available in the GraphQL service.
The JSON objects returned by the GraphQL service will be converted to Java objects.

[role="code_command hotspot file=0" ,subs="quotes"]
----
#Replace the Maven project file.#
`client/pom.xml`
----

The [hotspot=graphQLClientDependency file=0]`smallrye-graphql-client` dependency 
includes the classes used to interact with a GraphQL service.

[role="code_command hotspot file=1" ,subs="quotes"]
----
#Replace the server configuration file.#
`client/src/main/liberty/config/server.xml`
----

The [hotspot=url file=1]`graphql.server` variable is defined in the [hotspot file=1]`server.xml` file.
This variable defines where the GraphQL client will make its requests to.

[role="code_command hotspot file=2" ,subs="quotes"]
----
#Create the `GraphQlClient` interface.#
`client/src/main/java/io/openliberty/guides/client/api/GraphQlClient.java`
----

The [hotspot file=2]`GraphQlClient` interface is annotated with the
[hotspot=clientApi file=2]`@GraphQlClient` annotation.
This annotation denotes that this interface will be used to create a typesafe GraphQL client.

Inside the interface, a function header is written for each resolver available in the GraphQL service.
The names of the functions match the names of the resolvers in the GraphQL schema.
Resolvers that require input variables have the input variables passed in using the
[hotspot=systemInfo hotspot=systemLoad hotspot=editNote file=2]`@Name` annotation on the function inputs.
The return types of the functions should match those of the GraphQL resolvers.

For example, the [hotspot=systemInfo file=2]`system()` function maps to the `system` resolver.
The resolver returns a `system` object, which is described by the `SystemInfo` class.
Thus, the [hotspot=systemInfo file=2]`system()` function returns the type `SystemInfo`.

Because the [hotspot=editNote file=2]`editNote` resolver is for a `mutation` operation,
it has the [hotspot=mutationTag file=2]`@Mutation` annotation on it.
If this annotation was not placed on the function, it would be treated as if it mapped to a `query` operation.

// file 0
pom.xml
[source, xml, linenums, role='code_column hide_tags=copyright']
----
include::finish/client/pom.xml[]
----

// file 1
server.xml
[source, xml, linenums, role='code_column hide_tags=copyright']
----
include::finish/client/src/main/liberty/config/server.xml[]
----

// file 2
GraphQlClient.java
[source, java, linenums, role='code_column hide_tags=copyright']
----
include::finish/client/src/main/java/io/openliberty/guides/client/api/GraphQlClient.java[]
----

== Great work! You're done!

You just created a GraphQL client microservce!

include::{common-includes}/attribution.adoc[]

// ------------ END ------------
