// Copyright (c) 2021 IBM Corporation and others.
// Licensed under Creative Commons Attribution-NoDerivatives
// 4.0 International (CC BY-ND 4.0)
//   https://creativecommons.org/licenses/by-nd/4.0/
//
// Contributors:
//     IBM Corporation
//
:projectid: graphql-client
:page-layout: guide-multipane
:page-duration: 20 minutes
:page-releasedate: 2021-11-11
:page-essential: false
:page-description: Learn how to use a GraphQL client to run GraphQL queries and mutations.
:page-tags: ['MicroProfile', 'Jakarta EE']
:page-related-guides: ['graphql-intro']
:page-permalink: /guides/{projectid}
:common-includes: https://raw.githubusercontent.com/OpenLiberty/guides-common/prod
:imagesdir: /img/guide/{projectid}
:source-highlighter: prettify
:page-seo-title: Implementing a GraphQL client microservice to run GraphQL queries and mutations
:page-seo-description: A tutorial with examples on how to use the third-party Smallrye GraphQL client API to run GraphQL queries and mutations
:guide-author: Open Liberty
= Running GraphQL queries and mutations using a GraphQL client

[.hidden]
NOTE: This repository contains the guide documentation source. To view the guide in published form,
view it on the https://openliberty.io/guides/{projectid}.html[Open Liberty website].

Learn how to use a GraphQL client to run GraphQL queries and mutations.

== What you'll learn

You will learn how to create a GraphQL client microservice.

GraphQL is an open source data query language.
Unlike REST APIs, each `POST` request sent to a GraphQL service goes to a single HTTP endpoint.
To learn more about GraphQL, see our https://openliberty.io/guides/graphql-intro.html[GraphQL intro guide^].

You'll start with the GraphQL service created as part of our GraphQL intro guide.
You'll then use the https://github.com/smallrye/smallrye-graphql/tree/main/client/api[SmallRye GraphQL client^]
to create a `client` microservice that will make requests to the GraphQL service.
The results of the requests will be displayed at REST endpoints.
OpenAPI will be used to help make the requests and display the data.
To learn more about OpenAPI, check out the 
https://openliberty.io/guides/microprofile-openapi.html[Documenting RESTful APIs] guide.

== Additional prerequisites

Before you begin, Docker needs to be installed.
For installation instructions, refer to the https://docs.docker.com/get-docker/[official Docker documentation^].
You will build and run the application in Docker containers.

Make sure to start your Docker daemon before you proceed.

///////////////////////////
// Getting started
///////////////////////////

[role='command']
include::{common-includes}/gitclone.adoc[]

// No "Try what you'll build" because of multiple services, will take too long

== Implementing a GraphQL client

Navigate to the `start` directory to begin.

The https://github.com/smallrye/smallrye-graphql/tree/main/client/api[SmallRye GraphQL client^]
will be used to implement the GraphQL client service.
A client interface will be created.
The interface will contain a function for each resolver available in the GraphQL service.
The JSON objects returned by the GraphQL service will be converted to Java objects.

[role="code_command hotspot file=0" ,subs="quotes"]
----
#Replace the Maven project file.#
`client/pom.xml`
----

The [hotspot=graphQLClientDependency file=0]`smallrye-graphql-client` dependency 
includes the classes used to interact with a GraphQL service.

[role="code_command hotspot file=1" ,subs="quotes"]
----
#Replace the server configuration file.#
`client/src/main/liberty/config/server.xml`
----

The [hotspot=url file=1]`graphql.server` variable is defined in the [hotspot file=1]`server.xml` file.
This variable defines where the GraphQL client will make its requests to.

[role="code_command hotspot file=2" ,subs="quotes"]
----
#Create the `GraphQlClient` interface.#
`client/src/main/java/io/openliberty/guides/client/api/GraphQlClient.java`
----

The [hotspot file=2]`GraphQlClient` interface is annotated with the
[hotspot=clientApi file=2]`@GraphQlClient` annotation.
This annotation denotes that this interface will be used to create a typesafe GraphQL client.

Inside the interface, a function header is written for each resolver available in the GraphQL service.
The names of the functions match the names of the resolvers in the GraphQL schema.
Resolvers that require input variables have the input variables passed in using the
[hotspot=systemInfo hotspot=systemLoad hotspot=editNote file=2]`@Name` annotation on the function inputs.
The return types of the functions should match those of the GraphQL resolvers.

For example, the [hotspot=systemInfo file=2]`system()` function maps to the `system` resolver.
The resolver returns a `system` object, which is described by the `SystemInfo` class.
Thus, the [hotspot=systemInfo file=2]`system()` function returns the type `SystemInfo`.

Because the [hotspot=editNote file=2]`editNote` resolver is for a `mutation` operation,
it has the [hotspot=mutationTag file=2]`@Mutation` annotation on it.
If this annotation was not placed on the function, it would be treated as if it mapped to a `query` operation.

[role="code_command hotspot file=3" ,subs="quotes"]
----
#Create the `ClientResource` class.#
`client/src/main/java/io/openliberty/guides/client/ClientResource.java`
----

The [hotspot file=3]`ClientResource` class uses the [hotspot file=2]`GraphQlClient` interface
to make requests to the GraphQL service and display the results.
In a real application, you would be making requests to an external GraphQL API,
or you would be doing further manipulation of the data after retrieval.

The `GraphQlClient` interface is used in a [hotspot=clientBuilder file=3]`GraphQLClientBuilder`
to create an object that implements the interface and can interact with the GraphQL service.
It will make requests to the URL specified by the [hotspot=url file=1]`graphql.server` variable
in the `server.xml` in the previous steps of this guide.
The client is then used in the [hotspot=clientUsed1 file=3]`querySystem()`,
[hotspot=clientUsed2 file=3]`querySystemLoad()`, and[hotspot=clientUsed3 file=3]`editNote()` functions.


// file 0
pom.xml
[source, xml, linenums, role='code_column hide_tags=copyright']
----
include::finish/client/pom.xml[]
----

// file 1
server.xml
[source, xml, linenums, role='code_column hide_tags=copyright']
----
include::finish/client/src/main/liberty/config/server.xml[]
----

// file 2
GraphQlClient.java
[source, java, linenums, role='code_column hide_tags=copyright']
----
include::finish/client/src/main/java/io/openliberty/guides/client/api/GraphQlClient.java[]
----

// file 3
ClientResource.java
[source, java, linenums, role='code_column hide_tags=copyright']
----
include::finish/client/src/main/java/io/openliberty/guides/client/ClientResource.java[]
----

== Building and running the application

From the `start` directory, run the following commands:

[role='command']
----
mvn -pl models install
mvn clean package
----

The `mvn install` command compiles and packages the object types you created to a `.jar` file.
This allows them to be used by the `system` and `graphql` services.
The `mvn package` command packages the `system` and `graphql` services. 

Dockerfiles have already been set up for you.
Build your Docker images with the following commands:

[role='command']
----
docker build -t system:1.0-java8-SNAPSHOT --build-arg JAVA_VERSION=java8 system/.
docker build -t system:1.0-java11-SNAPSHOT --build-arg JAVA_VERSION=java11 system/.
docker build -t graphql:1.0-SNAPSHOT graphql/.
docker build -t client:1.0-SNAPSHOT client/.
----

Run these Docker images using the provided `startContainers` script.
The script will create a network for the services to communicate through.
It will create the two `system` services, a GraphQL service, and a `client` service that will interact with the GraphQL service.

include::{common-includes}/os-tabs.adoc[]

[.tab_content.windows_section]
--
[role='command']
```
.\scripts\startContainers.bat
```
--

[.tab_content.mac_section.linux_section]
--
[role='command']
```
./scripts/startContainers.sh
```
--

The containers may take some time to become available.

== Accessing the application

== Great work! You're done!

You just created a GraphQL client microservce!

include::{common-includes}/attribution.adoc[]

// ------------ END ------------
